on:
  #push
  push:
    #branches:
    #  - master
    #tags:
    #  - dailyfinal
    paths:
      - data/covid19za_provincial_cumulative_timeline_confirmed.csv

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Ensure Data Directory Exists
      run: |
        mkdir -p data/calc
        ls
    - name: Setup Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scipy IPython
    - name: Run Jupyter Notebook and Export csv
      uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "notebooks/Realtime R0.ipynb"
        params: ""
        isReport: False
        poll: True

    - name: Commit csv Changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: "Schalk van Heerden"
        author_email: schalkv@heerden.com
        message: "Ro notebook action run"
        add: "data/calc/calculated_r0_sa_provincial_cumulative.csv"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
